-- COPIAR Y PEGAR ESTO EN EL COMMAND LINE DE MySQL, Ó EN MySQL WORKBENCH.
ALTER USER 'root'@'localhost' IDENTIFIED BY 'SamBS0279';
ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'SamBS0279';
FLUSH PRIVILEGES;